### ISSUE TITLE
Startet nicht - viele Fehler im Log

### ISSUE THREAD

**Issue by Michaelnorge** [iobroker-community-adapters/ioBroker.tr-064-community#42]
Ich hatte die community-Version parallel zur "alten" Version installiert, um die Ip-Adressen rüber zu kopieren.
Danach Habe ich alle meine Scripte, die mit tr-064 zu tun haben umgeschrieben.

Als alles lief, habe ich die "alte" Instanz und den Adapter gelöscht.
Leider war danach auch die Community-Instanz verschwunden, die ich neu hinzugefügt habe.

Jetzt startet die Version nicht mehr. Weder eine Neuinstallation des Adapters noch ein Neustart des ioBrokers haben etwas gebracht.

2019-05-29 05:59:41.850 - error: Caught by controller[0]: module.js:550
--
2019-05-29 05:59:41.851 - error: Caught by controller[0]: throw err;
2019-05-29 05:59:41.851 - error: Caught by controller[0]: ^
2019-05-29 05:59:41.851 - error: Caught by controller[0]: Error: Cannot find module 'soef'
2019-05-29 05:59:41.852 - error: Caught by controller[0]: at Function.Module._resolveFilename (module.js:548:15)
2019-05-29 05:59:41.852 - error: Caught by controller[0]: at Function.Module._load (module.js:475:25)
2019-05-29 05:59:41.852 - error: Caught by controller[0]: at Module.require (module.js:597:17)
2019-05-29 05:59:41.852 - error: Caught by controller[0]: at require (internal/module.js:11:18)
2019-05-29 05:59:41.852 - error: Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.tr-064-community/lib/calllist.js:3:12)
2019-05-29 05:59:41.852 - error: Caught by controller[0]: at Module._compile (module.js:653:30)
2019-05-29 05:59:41.853 - error: Caught by controller[0]: at Object.Module._extensions..js (module.js:664:10)
2019-05-29 05:59:41.853 - error: Caught by controller[0]: at Module.load (module.js:566:32)
2019-05-29 05:59:41.853 - error: Caught by controller[0]: at tryModuleLoad (module.js:506:12)
2019-05-29 05:59:41.853 - error: Caught by controller[0]: at Function.Module._load (module.js:498:3)
2019-05-29 05:59:41.853 - error: host.ioBroker-RasPi instance system.adapter.tr-064-community.0 terminated with code 1 ()

**Comment by Michaelnorge** [comment]
Hab rausgefunden, daß die Community-Version wohl den Original-Adapter braucht.
Wäre gut, daß in der ReadMe anzugeben (falls ich es nicht überlesen habe), damit Anderen nicht das gleiche Missgeschick passiert!

**Comment by Apollon77** [comment]
Bitte neu die Community Version installieren.
